language: node_js
node_js:
  - "7"

branches:
  only:
  - dev

before_install:
  - chmod +x ./scripts/PRsanitycheck.py

before_script:
  - ./scripts/PRsanitycheck.py

script:
  - npm install
  - NODE_ENV=production browserify -t brfs src/app.js -o dist/js/bundle.js

cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  on:
    branch: dev
